# -*- coding: utf-8 -*-
"""Perro o gato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihKaQyE3GdznpK8s7nn2scLuWgiJEfV0

# Preparación de los datos
"""

!pip install kagglehub

import kagglehub

path = kagglehub.dataset_download("karakaggle/kaggle-cat-vs-dog-dataset")

print("Ruta del dataset:", path)

import os
import numpy as np
from PIL import Image


IMG_SIZE = 64
N_PER_CLASS = 1000

# Cambia esta ruta si en tu caso PetImages está en otra carpeta
base_dir = os.path.join(path, "kagglecatsanddogs_3367a", "PetImages")

cat_dir = os.path.join(base_dir, "Cat")
dog_dir = os.path.join(base_dir, "Dog")

print("Carpeta gatos:", cat_dir)
print("Carpeta perros:", dog_dir)

def cargar_imagenes(carpeta, etiqueta, n_imagenes, img_size=64):
    X = []
    Y = []

    archivos = os.listdir(carpeta)
    contador = 0

    for archivo in archivos:
        if contador >= n_imagenes:
            break

        ruta = os.path.join(carpeta, archivo)

        try:
            img = Image.open(ruta).convert("RGB")
            img = img.resize((img_size, img_size))

            img_array = np.array(img) / 255.0

            X.append(img_array)
            Y.append(etiqueta)

            contador += 1

        except:
            continue

    return np.array(X), np.array(Y)

X_cat, Y_cat = cargar_imagenes(cat_dir, etiqueta=1, n_imagenes=N_PER_CLASS, img_size=IMG_SIZE)
X_dog, Y_dog = cargar_imagenes(dog_dir, etiqueta=0, n_imagenes=N_PER_CLASS, img_size=IMG_SIZE)

print("Gatos cargados:", X_cat.shape)
print("Perros cargados:", X_dog.shape)

X = np.concatenate([X_cat, X_dog], axis=0)
Y = np.concatenate([Y_cat, Y_dog], axis=0)

print("X shape:", X.shape)
print("Y shape:", Y.shape)

np.random.seed(42)

indices = np.random.permutation(len(X))

X = X[indices]
Y = Y[indices]

print(Y)

m = len(X)

m_train = 1800
m_test = m - m_train

X_train = X[:m_train]
Y_train = Y[:m_train]

X_test = X[m_train:]
Y_test = Y[m_train:]

print("X_train:", X_train.shape)
print("Y_train:", Y_train.shape)

print("X_test:", X_test.shape)
print("Y_test:", Y_test.shape)

X_train_flatten = X_train.reshape(X_train.shape[0], -1)
X_test_flatten = X_test.reshape(X_test.shape[0], -1)

print("X_train_flatten:", X_train_flatten.shape)
print("X_test_flatten:", X_test_flatten.shape)

X_train_final = X_train_flatten.T
X_test_final = X_test_flatten.T

Y_train_final = Y_train.reshape(1, -1)
Y_test_final = Y_test.reshape(1, -1)

print("X_train_final:", X_train_final.shape)
print("Y_train_final:", Y_train_final.shape)

print("X_test_final:", X_test_final.shape)
print("Y_test_final:", Y_test_final.shape)

np.savez(
    "datos_gatos_perros_15.npz",
    X_train=X_train_final,
    Y_train=Y_train_final,
    X_test=X_test_final,
    Y_test=Y_test_final
)

"""# Red una neurona"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(z):
  return 1 / (1 + np.exp(-z))

def inicializar_parametros(n_x):
    np.random.seed(1)

    W = np.random.randn(1, n_x) * 0.01
    b = 0.0

    return W, b

def forward_propagation(W,X,b):
  Z = np.dot(W,X)+b
  A = sigmoid(Z)

  return A

def calcular_costo(A, Y):
    m = Y.shape[1]

    epsilon = 1e-8

    costo = -(1/m) * np.sum(
        Y * np.log(A + epsilon) +
        (1 - Y) * np.log(1 - A + epsilon)
    )

    return float(costo)

def backward_propagation(X,Y,A):
  m = X.shape[1]

  dZ= A-Y

  dW = (1/m)*np.dot(dZ,X.T)
  db = (1/m)*np.sum(dZ)
  return dW, db

def actualizar_parametros(W,b, dW, db, alpha):
  W= W-alpha*dW
  b= b-alpha*db
  return W,b

def modelo_una_capa(X, Y, num_iteraciones=10000, alpha=0.005):
  n_x= X.shape[0]
  W, b = inicializar_parametros(n_x)

  costos=[]
  for i in range(num_iteraciones):
    A=forward_propagation(W,X,b)
    costo=calcular_costo(A,Y)
    dW,db=backward_propagation(X,Y,A)
    W,b=actualizar_parametros(W,b,dW,db, alpha)

    if i % 100 == 0:
      costos.append(costo)
    if i % 500 == 0:
      print(f"iteración {i}: costo = {costo}")
  parametros ={
      "W": W,
      "b": b
  }

  return parametros, costos

X_train = X_train.reshape(X_train.shape[0], -1).T
X_test = X_test.reshape(X_test.shape[0], -1).T

Y_train = Y_train.reshape(1, -1)
Y_test = Y_test.reshape(1, -1)

print("X_train:", X_train.shape)
print("Y_train:", Y_train.shape)
print("X_test:", X_test.shape)
print("Y_test:", Y_test.shape)

parametros,costos = modelo_una_capa(X_train,Y_train,num_iteraciones=15000,alpha=0.005)

def predecir(X, parametros):
    W = parametros["W"]
    b = parametros["b"]

    A = forward_propagation(W, X, b)

    predicciones = A > 0.5

    return predicciones.astype(int), A

Y_pred_train, prob_train = predecir(X_train, parametros)
Y_pred_test, prob_test = predecir(X_test, parametros)

precision_train = 100 - np.mean(np.abs(Y_pred_train - Y_train)) * 100
precision_test = 100 - np.mean(np.abs(Y_pred_test - Y_test)) * 100

print("Precisión en entrenamiento:", precision_train, "%")
print("Precisión en prueba:", precision_test, "%")

for i in range(X_test.shape[1]):
    img = X_test[:, i].reshape(64, 64, 3)

    pred = Y_pred_test[0, i]
    real = Y_test[0, i]
    prob = prob_test[0, i]

    if pred == 1:
        texto_pred = "Gato"
    else:
        texto_pred = "Perro"

    if real == 1:
        texto_real = "Gato"
    else:
        texto_real = "Perro"

    plt.imshow(img)
    plt.title(f"Predicción: {texto_pred} | Real: {texto_real} | Prob gato: {prob:.3f}")
    plt.axis("off")
    plt.show()

